---
title: "sci-CAR: multimodal single cell sequencing using combinatoral indexing"
author: "Kelly Eckenrode"
date: "6/23/2020"
output: html_document
---
## [Joint profiling of chromatin accessibility and gene expression in thousands of single cells](https://science.sciencemag.org/content/361/6409/1380)
 
Science,  Cao, J., Cusanovich, D. A., Ramani, V., Aghamirzaie, D., Pliner, H. A., Hill, A. J., … Shendure, J. (2018)  doi:10.1126/science.aau0730 

A 2018 proof of concept paper on a new single cell co-assay experiment method: sci-CAR (single cell **c**hromatin **a**ccessibility and **R**NA-seq). sci-CAR allows for simultaneous measurements of mRNA and chromatin accessibility from ~16,000 nuclei. How can sci-CAR measure nearly 1000X more cells than other single cell multimodal methods? Combinatorial indexing. 

What makes sci-CAR so powerful in comparison to other single cell platforms is the combinatorial indexing method. Combinatorial indexing enables tracking of individual sequence molecules (in this case: mRNA and Tn5 DNA tags) to the same cell because of unique molecular identifier (UMI) adapters. UMIs are nucleotide sequences that act as barcodes. UMIs in are introduced in both the 3’ poly-A tail of mRNAs amplification and during tagmentation (**tagmentation** is when a transposon cleaves and adds a nucleotide sequence tag on double-stranded DNA) process of Tn5. 

In short, **combinatorial indexing molecular material allows for integrated analysis across modalities**. sci-CAR is able to accurately correlate RNA-seq data with ATAC-seq to the correct organism in a barnyard quality control experiment (mixing human and mouse cells together). Initial efforts to cluster sci-ATAC-seq profiles failed to discover the expected diversity of cell types, likely due to the sparsity of the data. But, by clustering cells based on RNA expression profiles and aggregated chromatin accessibility profiles uncovered 22,000 regulatory elements. And, by using covariance of differential RNA expression and differential chromatin accessibility, Cao et al. linked new distal elements to gene expression. Sometimes, chromatin accessibility correlated better with a distal element than its own promoter. Links between distal cis-regulatory elements and their target genes can be useful for explaining differential expression across cell types

Our group had comments and questions on the 3 main types of points, either experimental, analysis, and biological.

**Experimental**

* Only a subset of the nuclei have both modalities. Maybe linked to the extreme sparsity? Both modalities have similar missingness. Does splitting the lysate contribute to sparsity?

* The architecture of the genome is important to consider when thinking about technical biases, like a short gene might be entirely exposed, but a long gene is exposed in components. 

* Sequencing depth vs number of cells: design question. With ATAC, you can only get two reads per loci per cell (2 chromosomes), so you need a lot of cells for replication and peak calling (is a peak where you see two overlapping reads?). May be partially responsible for low correlation between ATAC and RNA-seq?

**Analysis**

* Complexity of ATAC-seq library compared to single-cell unimodal and bulk ATAC-seq: shallow sequencing is problematic, what is a peak if you only have 7000 reads in the whole genome?

* Is there any kind of “integrated” toy data set for this method, i.e. a common ground for method development.

* Is there standardized software for downstream analysis? But most of the work is done before the experiment, to prep the indexing methods.

**Biological**

* Gene regulation network including the epigenome information. Would this data be a good candidate, maybe not because of the lack of overlap between modalities.

* Does the accessibility and expression always need to be differential?

Although few sci-CAR datasets are currently available, there is consensus that combinatorial indexing will continue to be at the frontiers of single cell multimodal methodologies. The single cell sequencing field is moving quickly, so stay tuned for more SCMM journal club summaries!






